# fly.toml app configuration file generated for seminar-runner-remote on 2026-02-08T02:08:44+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "seminar-runner-remote"
primary_region = "nrt"

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[build]
  dockerfile = "Dockerfile"
